Epoch 1: Train Loss: 4894.7842, Train Vis Loss: 1.2471, Val Loss: 1.1407, Train Acc: 43.99%, Val Accuracy: 59.63%, Train F1 Score: 22.38%, Val F1 Score: 14.94%
For class normal the Train F1: 62.45% and Val F1: 74.71%
For class AVNRT the Train F1: 27.02% and Val F1: 0.00%
For class AVRT the Train F1: 6.53% and Val F1: 0.00%
For class concealed the Train F1: 9.27% and Val F1: 0.00%
For class EAT the Train F1: 6.63% and Val F1: 0.00%
Time taken for epoch 1: 0.94 minutes
Epoch 2: Train Loss: 4200.9799, Train Vis Loss: 0.9352, Val Loss: 1.1447, Train Acc: 70.98%, Val Accuracy: 59.63%, Train F1 Score: 31.56%, Val F1 Score: 14.94%
For class normal the Train F1: 84.26% and Val F1: 74.71%
For class AVNRT the Train F1: 52.82% and Val F1: 0.00%
For class AVRT the Train F1: 7.64% and Val F1: 0.00%
For class concealed the Train F1: 12.64% and Val F1: 0.00%
For class EAT the Train F1: 0.44% and Val F1: 0.00%
Time taken for epoch 2: 0.87 minutes
Epoch 3: Train Loss: 3926.6300, Train Vis Loss: 0.7872, Val Loss: 1.1764, Train Acc: 75.33%, Val Accuracy: 59.63%, Train F1 Score: 33.35%, Val F1 Score: 14.94%
For class normal the Train F1: 87.72% and Val F1: 74.71%
For class AVNRT the Train F1: 63.05% and Val F1: 0.00%
For class AVRT the Train F1: 10.40% and Val F1: 0.00%
For class concealed the Train F1: 4.78% and Val F1: 0.00%
For class EAT the Train F1: 0.83% and Val F1: 0.00%
Time taken for epoch 3: 0.86 minutes
Epoch 4: Train Loss: 3788.5450, Train Vis Loss: 0.7003, Val Loss: 1.3291, Train Acc: 76.86%, Val Accuracy: 23.85%, Train F1 Score: 37.29%, Val F1 Score: 7.70%
For class normal the Train F1: 88.54% and Val F1: 0.00%
For class AVNRT the Train F1: 67.58% and Val F1: 38.52%
For class AVRT the Train F1: 24.63% and Val F1: 0.00%
For class concealed the Train F1: 0.19% and Val F1: 0.00%
For class EAT the Train F1: 5.50% and Val F1: 0.00%
Time taken for epoch 4: 0.87 minutes
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f28d415e660>
Traceback (most recent call last):
  File "/home/tzikos/anaconda3/envs/KUThesis/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 1479, in __del__
    self._shutdown_workers()
  File "/home/tzikos/anaconda3/envs/KUThesis/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 1443, in _shutdown_workers
    w.join(timeout=_utils.MP_STATUS_CHECK_INTERVAL)
  File "/home/tzikos/anaconda3/envs/KUThesis/lib/python3.12/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tzikos/anaconda3/envs/KUThesis/lib/python3.12/multiprocessing/popen_fork.py", line 40, in wait
    if not wait([self.sentinel], timeout):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tzikos/anaconda3/envs/KUThesis/lib/python3.12/multiprocessing/connection.py", line 1135, in wait
    ready = selector.select(timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tzikos/anaconda3/envs/KUThesis/lib/python3.12/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt:
Traceback (most recent call last):
  File "/home/tzikos/anaconda3/envs/KUThesis/lib/python3.12/runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tzikos/anaconda3/envs/KUThesis/lib/python3.12/runpy.py", line 88, in _run_code
    exec(code, run_globals)
  File "/home/tzikos/.vscode/extensions/ms-python.debugpy-2024.4.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/home/tzikos/.vscode/extensions/ms-python.debugpy-2024.4.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/tzikos/.vscode/extensions/ms-python.debugpy-2024.4.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/home/tzikos/.vscode/extensions/ms-python.debugpy-2024.4.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tzikos/.vscode/extensions/ms-python.debugpy-2024.4.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/tzikos/.vscode/extensions/ms-python.debugpy-2024.4.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/home/tzikos/Desktop/KULeuvenThesis/main.py", line 127, in <module>
    CVtrain(modelStr=MODEL_STR, learningRate=LEARNING_RATE_BERT, epochs=1000, classWeights=classWeights,
  File "/home/tzikos/Desktop/KULeuvenThesis/models.py", line 804, in CVtrain
    trainVisLoss += visLoss.item()
                    ^^^^^^^^^^^^^^
KeyboardInterrupt
Exception ignored in: <module 'threading' from '/home/tzikos/anaconda3/envs/KUThesis/lib/python3.12/threading.py'>
Traceback (most recent call last):
  File "/home/tzikos/anaconda3/envs/KUThesis/lib/python3.12/threading.py", line 1622, in _shutdown
    lock.acquire()
KeyboardInterrupt: